### PR TITLE
Added LGPLv3 License

### PR DESCRIPTION
**Pull request by fharding1**

### CODE REVIEW

**Comment by BrendanBurkhart** [comment]
@calebeby @howardabrams

**Comment by calebeby** [comment]
Why LGPL over MIT? What are the differences?

**Comment by BrendanBurkhart** [comment]
The LGPL is a bit stricter about preventing other people from charging money to use it, but not as copyleft as the GPL.

**Comment by calebeby** [comment]
OK

**Comment by fharding1** [comment]
It's a .md now.

**Comment by BrendanBurkhart** [comment]
I would still like to get mentor approval, but I think this is good.

**Comment by fharding1** [comment]
Oh...

**Comment by BrendanBurkhart** [comment]
No, we can totally have a license set for now, I just want a mentor to give advice at some point, we can always change the lease license later.

**Comment by fharding1** [comment]
Alright cool :+1:

**Pull request merged**
