### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by BrendanBurkhart**

### CODE REVIEW

**Comment by calebeby** [comment]
Travis CI anyone?

**Comment by calebeby** [comment]
Also what happened to docker?

**Comment by calebeby** [comment]
And the README?

**Comment by BrendanBurkhart** [comment]
Docker was for testing so until production is dockerized is unnecessary. Tests are coming.... eventually....
And @fharding1 we should add the README, I think it should probably be completely rewritten as this point though

**Comment by fharding1** [comment]
We shouldn't write the readme because there's literally nothing to write yet. We only need to write the readme once we add docker and stuff. Otherwise the readme is just a list of environment variables and `go build` and `./scouting-backend`

**Comment by fharding1** [comment]
Ignore that accidental close :)

**Pull request merged**
