### PR TITLE
Moved all middlewares to Run instead of initializeRouter

### LINKED ISSUE #52: Put all handlers in one place
Some are in Run and some are in initializeRouter.

### PR DESCRIPTION
**Pull request by fharding1**
Fixes #52

### CODE REVIEW

**Comment by BrendanBurkhart** [comment]
You should be wrapping the router, not s.Handler (which I don’t think we need any more).

**Comment by fharding1** [comment]
Shouldn't you be in class? /s. Fixed. I'm dumb 👍

**Comment by fharding1** [comment]
Ok should be good now.

**Comment by BrendanBurkhart** [comment]
I like moving the middlewares out of run. How were the tests able to pass without tollbooth?

**Comment by fharding1** [comment]
Tollbooth just rate limits which I'm pretty sure is irrelevant to localhost (which is obviously where the tests are running).

**Comment by BrendanBurkhart** [comment]
But the code still invokes the tollbooth middleware, it seems like it should have complained when it compiled.

**Comment by fharding1** [comment]
No it didn't, I removed all the tollbooth stuff for a second for testing and commited forgetting I had done that.

**Pull request merged**
